buildimage:
	@FAKEROOTDONTTRYCHOWN=1 ${BUILDROOT_DIR}/host/bin/fakeroot -- $(SKIFF_CURRENT_CONF_DIR)/scripts/buildimage.sh
run:
	@$(SKIFF_CURRENT_CONF_DIR)/scripts/run.sh
exec:
	@$(SKIFF_CURRENT_CONF_DIR)/scripts/exec.sh
