format:
	@$(SKIFF_CURRENT_CONF_DIR)/scripts/format_sd.sh

install:
	@$(SKIFF_CURRENT_CONF_DIR)/scripts/install_sd.sh

buildimage:
	@$(SKIFF_CURRENT_CONF_DIR)/scripts/build_image.sh

# alias to buildimage
create-image: buildimage
