[Unit]
# Clear udev device unit dependency (we mask udev-trigger).
# /dev/ttyS0 exists via devtmpfs, no need for systemd device unit.
BindsTo=
After=

[Service]
ExecStart=
ExecStart=-/bin/sh -l
StandardInput=tty
StandardOutput=tty
StandardError=tty
